version: 2.1
parameters:
  running-file:
    type: enum
    enum:
      [
        search_fixedasset/searching_full_flow.jmx,
        search_fixedasset/searchingTC4.jmx,
        searching/searchStagingLoginMultipleTime.jmx,
        searching/searchBetaBypassLogin.jmx
      ]
    default: searching/searchStagingLoginMultipleTime.jmx

setup: true

orbs:
  aws-s3: circleci/aws-s3@3.0.0

executors:
  circleci-jmeter:
    docker:
      - image: justb4/jmeter:5.5

workflows:
  common-test:
    jobs:
      - job_test

jobs:
  job_test:
    executor: circleci-jmeter
    circleci_ip_ranges: true # opts the job into the IP ranges feature
    steps:
      - checkout
      - run:
          name: Make Results Directory
          command: mkdir results
      - run:
          name: Remove output login data
          command: rm -rf services/search_fixedasset/ouput/account.csv
      - run:
          name: Run test
          command: |
            jmeter -n -t services/<< pipeline.parameters.running-file >> -l results/runResults.csv -e -o results;
      - store_artifacts:
          path: ./results
