version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.0.0
  aws-eks: circleci/aws-eks@2.2
  kubernetes: circleci/kubernetes@1.3
  jq: circleci/jq@2.2.0

commands:
  setup-environment:
    steps:
      - jq/install
      - aws-cli/setup:
          role_arn: ${AWS_ROLE_ARN}
          profile_name: "qa-service-platform"
          session_duration: "1800"
      - kubernetes/install-kubectl:
          kubectl-version: v1.22.0
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: "load-test-cluster"
          aws-profile: "qa-service-platform"
          aws-region: ${AWS_DEFAULT_REGION}
      - run:
          name: install qapf-tools
          command: |
            echo "Download qapf"
            asseturl=$(curl -H "Authorization: token ${MINAMI_GITHUB_TOKEN}" https://api.github.com/repos/moneyforward/cqoo-qapf/releases/latest | jq -r '.assets[] | select(.name=="qapf.zip") | .url')
            curl -L -H "Authorization: token ${MINAMI_GITHUB_TOKEN}" -H "Accept:application/octet-stream" ${asseturl} >qapf.zip
            unzip qapf.zip
            chmod +x ./qapf

jobs:
  performance-test:
    docker:
      - image: cimg/base:current
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_ACCOUNT_ID: "056699753121"
    steps:
      - checkout
      - setup-environment
      - run:
          name: Conduct performance test
          command: |
            echo "Create workspace"
            ./qapf create-workspace aa-performance-jmeter

            echo "Upload scenarios to S3"
            ./qapf upload-test-scenarios -w aa-performance-jmeter -t jmeter -d ./

            echo "Prepare testing environment"
            ./qapf prepare-testing-environment -w aa-performance-jmeter -t jmeter -c ./jmeter-config.yaml

            echo "Conduct performance test"
            ./qapf conduct-perf-test -w aa-performance-jmeter -t jmeter -f services/corporate_tax/Table16_1_LoginOTP.jmx -s mfv_performance_test_notifications

workflows:
  aa-performance-test:
    jobs:
      - performance-test:
          context:
            - deploy-role-load-test-cluster
          filters:
            branches:
              only:
                - main
